### ISSUE TITLE
How do you run this locally? (NOT on heroku)

### ISSUE THREAD

**Issue by lovedoodle** [mars/heroku-js-runtime-env-buildpack#1]
Curious how I run this locally thanks!

**Comment by undrthemt** [comment]
@lovedoodle 
Run locally with heroku local command.
You can define env variables in .env file.

Here is the official document.
https://devcenter.heroku.com/articles/heroku-local

**Comment by mars** [comment]
@undrthemt, `heroku local` does not run this locally. This project is enabled by the runtime part of create-react-app-buildpack.

**Comment by mars** [comment]
Normally local work is in “development” mode which relies on the javascript framework’s dev mode, `npm start` for create-react-app.

This project does not specifically provide a local mode. If you really want to try to run it locally, the javascript bundle will need to be built in production mode, and then the runtime variables will need to be injected with the [script from create-react-app-inner-buildpack](https://github.com/mars/create-react-app-inner-buildpack/blob/master/.profile.d/inject_react_app_env.sh).
