### ISSUE TITLE
Trouble getting variables accessible in rails/react app

### ISSUE THREAD

**Issue by drj17** [mars/heroku-js-runtime-env-buildpack#3]
Here's my file structure

```
├── Procfile
├── README.md
├── app.json
├── backend
│   ├── public
├── frontend
│   ├── build
│   ├── config
│   ├── node_modules
│   ├── package.json
│   ├── public
│   ├── scripts
│   ├── src
│   ├── static.json
│   └── yarn.lock
├── package.json
└── yarn.lock
```

I'm trying to pass an ENV variable calls API_BASE_URL to my react app.

here's my .env file: 
```
REACT_APP_API_BASE_URL=http://localhost:8080/api/v2
JS_RUNTIME_TARGET_BUNDLE=../backend/public/static/js/*.js
```

in my frontend my package.json script I copy over the production build to my rails public folder:
```
    "deploy": "cp -a frontend/build/. backend/public/",
```

However, in my react app, the env variable REACT_APP_API_BASE_URL is always undefined.  Am I doing something wrong?

**Comment by mars** [comment]
Hi @drj17, this repo/module is dependent on the buildpack for build & runtime profile hook to make env vars available. See the README about that.

With Rails, or other server-side apps, I suggest building the `index.html` as a server-side template with env vars set dynamically into global variables via `<script>` element.

**Comment by mars** [comment]
Also, if you do manage to make this work for your unique situation, note that `JS_RUNTIME_TARGET_BUNDLE` should not be relative. It would need to be something starting with `/app` (the home directory on Heroku dynos) like `/app/backend/public/static/js/*.js`
